version: 2

project_name: external-dns-sacloud-webhook

builds:
  - id: webhook
    binary: external-dns-sacloud-webhook
    main: ./cmd/webhook
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.GitSha={{ .Commit }}

dockers:
  - id: docker-amd64
    use: buildx
    goarch: amd64
    image_templates:
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:amd64-{{ .Tag }}
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:amd64-latest
      - ghcr.io/sacloud/external-dns-sacloud-webhook:amd64-{{ .Tag }}
      - ghcr.io/sacloud/external-dns-sacloud-webhook:amd64-latest
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: docker-arm64
    use: buildx
    goarch: arm64
    image_templates:
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:arm64-{{ .Tag }}
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:arm64-latest
      - ghcr.io/sacloud/external-dns-sacloud-webhook:arm64-{{ .Tag }}
      - ghcr.io/sacloud/external-dns-sacloud-webhook:arm64-latest
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: dockerrc.sakuracr.jp/external-dns-sacloud-webhook:{{ .Tag }}
    image_templates:
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:amd64-{{ .Tag }}
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:arm64-{{ .Tag }}

  - name_template: dockerrc.sakuracr.jp/external-dns-sacloud-webhook:latest
    image_templates:
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:amd64-latest
      - dockerrc.sakuracr.jp/external-dns-sacloud-webhook:arm64-latest

  - name_template: ghcr.io/sacloud/external-dns-sacloud-webhook:{{ .Tag }}
    image_templates:
      - ghcr.io/sacloud/external-dns-sacloud-webhook:amd64-{{ .Tag }}
      - ghcr.io/sacloud/external-dns-sacloud-webhook:arm64-{{ .Tag }}

  - name_template: ghcr.io/sacloud/external-dns-sacloud-webhook:latest
    image_templates:
      - ghcr.io/sacloud/external-dns-sacloud-webhook:amd64-latest
      - ghcr.io/sacloud/external-dns-sacloud-webhook:arm64-latest
